//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningCard.OnlineLearningCardService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OnlineLearningCardService.IOnlineLobbyServiceModel")]
    public interface IOnlineLobbyServiceModel {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineLobbyServiceModel/JoinToLobby", ReplyAction="http://tempuri.org/IOnlineLobbyServiceModel/JoinToLobbyResponse")]
        bool JoinToLobby();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineLobbyServiceModel/JoinToLobby", ReplyAction="http://tempuri.org/IOnlineLobbyServiceModel/JoinToLobbyResponse")]
        System.Threading.Tasks.Task<bool> JoinToLobbyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineLobbyServiceModel/GetPublicIP", ReplyAction="http://tempuri.org/IOnlineLobbyServiceModel/GetPublicIPResponse")]
        string GetPublicIP();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineLobbyServiceModel/GetPublicIP", ReplyAction="http://tempuri.org/IOnlineLobbyServiceModel/GetPublicIPResponse")]
        System.Threading.Tasks.Task<string> GetPublicIPAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOnlineLobbyServiceModelChannel : LearningCard.OnlineLearningCardService.IOnlineLobbyServiceModel, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OnlineLobbyServiceModelClient : System.ServiceModel.ClientBase<LearningCard.OnlineLearningCardService.IOnlineLobbyServiceModel>, LearningCard.OnlineLearningCardService.IOnlineLobbyServiceModel {
        
        public OnlineLobbyServiceModelClient() {
        }
        
        public OnlineLobbyServiceModelClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OnlineLobbyServiceModelClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlineLobbyServiceModelClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlineLobbyServiceModelClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool JoinToLobby() {
            return base.Channel.JoinToLobby();
        }
        
        public System.Threading.Tasks.Task<bool> JoinToLobbyAsync() {
            return base.Channel.JoinToLobbyAsync();
        }
        
        public string GetPublicIP() {
            return base.Channel.GetPublicIP();
        }
        
        public System.Threading.Tasks.Task<string> GetPublicIPAsync() {
            return base.Channel.GetPublicIPAsync();
        }
    }
}
