//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningCard.OnlineLearningCardService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profile", Namespace="http://schemas.datacontract.org/2004/07/LearningCard.Model")]
    [System.SerializableAttribute()]
    public partial class Profile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Uri ImageSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, int[]> StatisticDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Uri ImageSource {
            get {
                return this.ImageSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageSourceField, value) != true)) {
                    this.ImageSourceField = value;
                    this.RaisePropertyChanged("ImageSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LanguageFile {
            get {
                return this.LanguageFileField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageFileField, value) != true)) {
                    this.LanguageFileField = value;
                    this.RaisePropertyChanged("LanguageFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, int[]> StatisticData {
            get {
                return this.StatisticDataField;
            }
            set {
                if ((object.ReferenceEquals(this.StatisticDataField, value) != true)) {
                    this.StatisticDataField = value;
                    this.RaisePropertyChanged("StatisticData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OnlineLearningCardService.IOnlineLobbyServiceModel")]
    public interface IOnlineLobbyServiceModel {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineLobbyServiceModel/JoinToLobby", ReplyAction="http://tempuri.org/IOnlineLobbyServiceModel/JoinToLobbyResponse")]
        bool JoinToLobby(LearningCard.OnlineLearningCardService.Profile prof);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineLobbyServiceModel/JoinToLobby", ReplyAction="http://tempuri.org/IOnlineLobbyServiceModel/JoinToLobbyResponse")]
        System.Threading.Tasks.Task<bool> JoinToLobbyAsync(LearningCard.OnlineLearningCardService.Profile prof);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineLobbyServiceModel/GetActiveUsers", ReplyAction="http://tempuri.org/IOnlineLobbyServiceModel/GetActiveUsersResponse")]
        LearningCard.OnlineLearningCardService.Profile[] GetActiveUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineLobbyServiceModel/GetActiveUsers", ReplyAction="http://tempuri.org/IOnlineLobbyServiceModel/GetActiveUsersResponse")]
        System.Threading.Tasks.Task<LearningCard.OnlineLearningCardService.Profile[]> GetActiveUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineLobbyServiceModel/GetPublicIP", ReplyAction="http://tempuri.org/IOnlineLobbyServiceModel/GetPublicIPResponse")]
        string GetPublicIP();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineLobbyServiceModel/GetPublicIP", ReplyAction="http://tempuri.org/IOnlineLobbyServiceModel/GetPublicIPResponse")]
        System.Threading.Tasks.Task<string> GetPublicIPAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOnlineLobbyServiceModelChannel : LearningCard.OnlineLearningCardService.IOnlineLobbyServiceModel, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OnlineLobbyServiceModelClient : System.ServiceModel.ClientBase<LearningCard.OnlineLearningCardService.IOnlineLobbyServiceModel>, LearningCard.OnlineLearningCardService.IOnlineLobbyServiceModel {
        
        public OnlineLobbyServiceModelClient() {
        }
        
        public OnlineLobbyServiceModelClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OnlineLobbyServiceModelClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlineLobbyServiceModelClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlineLobbyServiceModelClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool JoinToLobby(LearningCard.OnlineLearningCardService.Profile prof) {
            return base.Channel.JoinToLobby(prof);
        }
        
        public System.Threading.Tasks.Task<bool> JoinToLobbyAsync(LearningCard.OnlineLearningCardService.Profile prof) {
            return base.Channel.JoinToLobbyAsync(prof);
        }
        
        public LearningCard.OnlineLearningCardService.Profile[] GetActiveUsers() {
            return base.Channel.GetActiveUsers();
        }
        
        public System.Threading.Tasks.Task<LearningCard.OnlineLearningCardService.Profile[]> GetActiveUsersAsync() {
            return base.Channel.GetActiveUsersAsync();
        }
        
        public string GetPublicIP() {
            return base.Channel.GetPublicIP();
        }
        
        public System.Threading.Tasks.Task<string> GetPublicIPAsync() {
            return base.Channel.GetPublicIPAsync();
        }
    }
}
